Feature: Day 06: Guard Gallivant

    Scenario: Part 1, loading the map and finding the guard
        Given a map of the guard situation
        """
        ....#.....
        .........#
        ..........
        ..#.......
        .......#..
        ..........
        .#..^.....
        ........#.
        #.........
        ......#...
        """
        When you load the grid
        Then the location of the guard should be 4,6

    Scenario: Part 1, walking around
        Given a map of the guard situation
        """
        ....#.....
        .........#
        ..........
        ..#.......
        .......#..
        ..........
        .#..^.....
        ........#.
        #.........
        ......#...
        """
        When you load the grid
        Then the number of steps should be 123