
name: C# - 2024

on:
  push:
    paths:
    - "csharp/2024/**"
     
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet 9.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Build
      working-directory: ./csharp/2024
      run: dotnet build
    - name: Run tests
      working-directory: ./csharp/2024
      run: dotnet test --no-build
