
name: C# - 2024

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./csharp/2024
      run: dotnet build
    - name: Run tests
      working-directory: ./csharp/2024
      run: dotnet test --no-build
