name: C# 

on:
  push:
    paths:
      - "csharp/2023/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./csharp/2023
      run: dotnet build
    - name: Run tests
      working-directory: ./csharp/2023
      run: dotnet test --no-build
